[package]
name = "http-forward-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
nyquest = {version ="0.2.0", features=["async"] }
nyquest-preset = {version="0.2.0",features=["async"]}
tokio = { version = "1.47.1", features = ["full"] }
